#!/usr/bin/python
import string as s, random, os, subprocess, getpass
from os.path import exists

prompt = input("Do you want to make a new password? (y/n) ")

x=0
if prompt.lower() == "y":
    length = int(input("How many charecters do you want your password to have? "))
    numbers = input("Do you want numbers? (y/n) ")
    letters = input("Do you want letters? (y/n) ")
    charecters = input("Do you want charecters? (y/n) ")
    totalChoice = str()
    if numbers.lower() == "y": totalChoice = s.digits
    if letters.lower() == "y": totalChoice += s.ascii_letters
    if charecters.lower() == "y": totalChoice += s.punctuation
    x = 1
    passwd = "".join(random.choices(totalChoice, k=length))
    print(passwd)

if "passwd" not in locals() or input("Do you want to save this? (y/n)").lower() == "y":
    location = f"{os.path.expanduser('~')}/.pass.txt"
    print(location)
    if not exists(location):
        os.mknod(location)
        os.system(f"chmod -r {location}")
    file = open(location, 'a')
    file.write("Name: " + str(input("What site/application is this for? ")) + "\n")
    file.write("Username: " + str(input("What is your user name for said site/application? ")) + "\n")
    if x == 0: passwd = getpass.getpass('What is your password? ')
    file.write("Password: " + str(passwd) + "\n\n")
